spring:
  application:
    name: espiel-spring-security
  datasource:
    url: jdbc:postgresql://localhost:5432/espiel_spring_security
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      whitelist: "/api/login,/api/register"
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}

keycloak:
  realm: espiel-spring-security-kc-rbac
  auth-server-url: http://localhost:8080
#  ssl-required: external
  resource: course-management
#  verify-token-audience: true
  credentials:
    secret: kr7Tc3UkoildNSuaNg4Njd3XCqBuwrCQ
  policy-enforcer-config:
#    enforcement-mode: PERMISSIVE
#    lazy-load-paths: true
    http-method-as-scope: true
    paths:
      - path: /api/login
        enforcement-mode: DISABLED
      - path: /api/register
        enforcement-mode: DISABLED
#  use-resource-role-mappings: true
  bearer-only: true
#  confidential-port: 0
#  grant_type: password
  securityConstraints:
#    - securityCollections:
#        - patterns:
#            - /api/login
#            - /api/register
    - authRoles: '*'
      securityCollections:
        - name: Secured
          patterns: /*
    - security-collections:
        - name: Public
          patterns:
            - /api/login
            - /api/register

server:
  port: 7070