spring:
  application:
    name: espiel-spring-security
  datasource:
    url: jdbc:postgresql://localhost:5432/espiel_spring_security
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 7070

keycloak:
  realm: espiel-spring-security-kc-rbac
  auth-server-url: http://localhost:8080
  resource: course-management
  bearer-only: true
  credentials:
    secret: kr7Tc3UkoildNSuaNg4Njd3XCqBuwrCQ
  policy-enforcer-config:
    http-method-as-scope: true
    paths:
      - path: /api/login
        enforcement-mode: DISABLED
      - path: /api/register
        enforcement-mode: DISABLED
  securityConstraints:
    - authRoles: '*'
      securityCollections:
        - name: Secured
          patterns: /*
    - security-collections:
        - name: Public
          patterns:
            - /api/login
            - /api/register
