spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/espiel_spring_security
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:test-secret}
  access-token-validity-in-seconds: 900
  refresh-token-validity-in-seconds: 604800